### ISSUE TITLE
Supporting QT5

### ISSUE THREAD

**Issue by ViktorNova** [marcusbritanicus/NewBreeze#12]
Do you plan to port your cool file manager to QT5?

**Comment by marcusbritanicus** [comment]
Yes indeed i do. I think much of the code is Qt5 ready. Some little bit needs to be corrected.

**Comment by marcusbritanicus** [comment]
NewBreeze now supports Qt5.

**Comment by ViktorNova** [comment]
Excellent! Can't wait to try it
