### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by lfdominguez** [marcusbritanicus/NewBreeze#14]
When compiling i was need change in the NBFileIO.cpp "#include <NBFileIO.hpp>" by "#include "NBFileIO.hpp" "

**Comment by marcusbritanicus** [comment]
NBFileIO.hpp should not be in any of the files at all. I'll check this out and fix it in the next commit.

**Comment by marcusbritanicus** [comment]
I have removed NBFileIO.cpp and NBFileIO.hpp from src.pro. You'll note be able to compile with out issues.
