### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by fdservices** [marcusbritanicus/NewBreeze#15]
Gui/Widgets/Buttons/NBPushButton.cpp:443:22: error: ‘QStyle’ has not been declared
  if ( btnOpt.state & QStyle::State_Enabled )

**Comment by marcusbritanicus** [comment]
I have just compiled a fresh copy. I did not get this error. Could you please tell me the platform and Qt version? Mine is 4.8.7 on Debian Testing.

**Comment by fdservices** [comment]
Sure: Arch and Qt5.8.0

Andrew

**Comment by marcusbritanicus** [comment]
Ah.. I think I need to fix a few files for Qt5. I'll update the repos by this weekend Qt5 fixes.

**Comment by fdservices** [comment]
Thank you very much

Andrew

**Comment by marcusbritanicus** [comment]
I think I have the Qt5 issues. Let me know if it compiles now.

**Comment by fdservices** [comment]
I got a lot further with the build this time, but still have an error:

Project ERROR: NewBreeze plugin interface header file not detected. 
Please set the envronmental variable NB_INCLUDES.

Sorry, but I do not know how to fix this.

Andrew

**Comment by marcusbritanicus** [comment]
Aaaah.....! My bad. Its a relic from the older NewBreeze 2.4. Fixed it.

**Comment by fdservices** [comment]
Thank you - will try again.

Andrew

**Comment by fdservices** [comment]
OK - compiled fine this time

On first run I got a segfault. But the second time I ran it, it was fine.

IT IS FAST!!!!! And very attractive!

I will be looking forward to further development.

Andrew

**Comment by marcusbritanicus** [comment]
I'm happy you liked it.
