### ISSUE TITLE
Android compilation

### ISSUE THREAD

**Issue by fntheirs** [marcusbritanicus/NewBreeze#16]
Hi! I'd like to use your library for my Android project. I tried with libarchive-qt but it needs some dependencies that I don't know if they are available for Android. Have you ever tried to compile your project for Android?

**Comment by marcusbritanicus** [comment]
NewBreeze is not meant for Android. It's a desktop file manager. If you want to use libarchive-qt for Android, here is the link: https://github.com/libarchive/libarchive/tree/master/contrib/android. You'll have to build libarchive for Android first. Mine is just a light wrapper on top of it.
