### ISSUE TITLE
Future Features

### ISSUE THREAD

**Issue by nathan2423** [marcusbritanicus/NewBreeze#18]
Your goals look fairly similar to what I am looking for,  Any possibility that you could incorporate any of the desired features I discussed here - http://www.donationcoder.com/forum/index.php?topic=44064.0

Which is primarily 

- On the left, a tree pane PLUS a favorites pane (drag and droppable from the file list in the center).  

- In the center, a standard File list for standard rename, delete, and similar file (including double-click to LAUNCH!) operations in middle.  This center pane is actually two separate file lists, with the one on the bottom all but minimized.  Two file lists for moving files between them is nice but not at all mandatory.

- On the right, a preview pane for viewing pictures, media, word processing files, etc that displays the currently-selected file in the middle pane.

PS - I am running MX16 and have made initial efforts to try to build, but I am not very good at compiling and have failed so far.

**Comment by marcusbritanicus** [comment]
I have some plans similar to yours, but on the whole, the changes you suggest are substantial, and I am not willing to make so many changes. The Right Pane, yes. I will add it in the future. I find the TreeView in the sidepanel messy, but have plans to add it anyway.
As for adding file to favorites, I am working on SuperStart, which will have support for files and folders bookmarking.
If you want help building a file manager for yourself, I'll try to help you as much as I can. Most of the features you want are not that complicated. You can use most of the Qt classes as is and make do. It would make a very lightweight and a feature rich FM.

**Comment by nathan2423** [comment]
Marcusbritanicus thank you very much for the detailed reply.  I appreciate your time in preparing it.    I am afraid I am not much of a programmer myself so I doubt I can start anything myself, but I very much appreciate your offer of help.  Your NewBreeze effort seems very well thought out and I am looking forward to testing it.  If you end up adding a preview pane at some point (the Right Pane) and then have bookmarking for files (in addition to folders) that will go a long way.  Thank you again!

**Comment by marcusbritanicus** [comment]
I have added an elementary `NBInfopanel` (RightPanel). It can at the moment show only Image previews. Previews for other file-types will be added in the coming days, or as a plugin. I've not yet decided.

**Comment by marcusbritanicus** [comment]
`SuperStart` is sufficiently refined that you can begin using it. There are some rough edges here and there that need to be sanded. I have not yet included a ContextMenu for SuperStart, it will take some time. Until then, try using SuperStart and let me know how it goes.

**Comment by nathan2423** [comment]
sorry for the dumb question but is Superstart part of newbreeze or a separate github project?
--------------------------------------------
On Mon, 8/7/17, Marcus Britanicus <notifications@github.com> wrote:

 Subject: Re: [marcusbritanicus/NewBreeze] Future Features (#18)
 To: "marcusbritanicus/NewBreeze" <NewBreeze@noreply.github.com>
 Cc: "nathan2423" <cicerosc@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Monday, August 7, 2017, 1:47 PM
 
 SuperStart is
 sufficiently refined that you can begin using it. There are
 some rough edges here and there that need to be sanded. I
 have not yet included a ContextMenu for SuperStart, it will
 take some time. Until then, try using SuperStart and let me
 know how it goes.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by marcusbritanicus** [comment]
Its a part of NewBreeze v3. To be more specific, its the browser equivalent of StartPage. Press "Ctrl+Shift+S" for settings and you can enable SuperStart
![screenshot_20170810_234656](https://user-images.githubusercontent.com/3350667/29185294-68f7afa8-7e26-11e7-9d7d-28815700d7aa.png)

**Comment by marcusbritanicus** [comment]
A basic context menu has been enabled for SuperStart. And several refinements have been made. I hope you are using and enjoying NewBreeze.
