### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: webkit webkitwidgets

### ISSUE THREAD

**Issue by probonopd** [marcusbritanicus/NewBreeze#21]
Getting `Project ERROR: Unknown module(s) in QT: webkit webkitwidgets` in https://travis-ci.org/probonopd/NewBreeze/builds/345883382#L1074. 

Are WebKit/WebKitWidgets mandadory requirements?

WebKit/WebKitWidgets are not mentioned on https://github.com/marcusbritanicus/NewBreeze#dependencies.

**Comment by probonopd** [comment]
Qt 5.9.3 from https://bugs.launchpad.net/~beineri/+archive/ubuntu/opt-qt593-trusty/+index?field.series_filter=trusty only has `qt59webchannel`  and `qt59webengine` packages but not `webkit` and `webkitwidgets`.

All things Web* seem to be the source of constant breakage in Qt because they seem not to know whether they want WebKit or WebEngine or WebKit again...

**Comment by probonopd** [comment]
Is there a way to build NewBreeze without any of the Qt Web* stuff? That would be my preference, since it also makes the resulting AppImage much smaller.

**Comment by marcusbritanicus** [comment]
WebKit is used in Plugins. since I was mainly developing using Qt4, it has remained unported. The two plugins, Default and MarkDown will have to rewritten. That will take some time. 
Until then, perhaps you can disable the two plugins?

**Comment by probonopd** [comment]
> Until then, perhaps you can disable the two plugins?

Yes, how would I do that?

**Comment by marcusbritanicus** [comment]
Edit the file `plugins.pro` in plugins subdir and remove MarkDown.
Then, edit the file `plugins/Default/Default.pro`. Comment out the lines 38-41 and 124, 125. I believe after that NewBreeze should compile properly. Also you'll have most part of Default plugin.

**Comment by probonopd** [comment]
Is there any way you could make this a compile option that that I wouldn't have to change your source code? That would be cleaner for an upcoming AppImage generation pull request. Thanks.

**Comment by marcusbritanicus** [comment]
I have been working on complete upgrade to Qt5 and was planning to retire Qt4. Since you're making an AppImage, I will speed up the process and release the modified version in a couple of days.

**Comment by marcusbritanicus** [comment]
For now, Qt5 uses `QtWebEngine` and Qt4 continues to use `QtWebKit`. In case issues arise in older versions of Qt5 (<5.5), I might re-enable webkit support for Qt5. `QtWebEngine` support for Qt5 will continue. [Beta2 Release](https://github.com/marcusbritanicus/NewBreeze/commit/8b5cfebae424fe1ac49bf061fd2273b57bc3608f)

**Comment by probonopd** [comment]
Thanks, started a new build at https://travis-ci.org/probonopd/NewBreeze/builds/346018669

**Comment by probonopd** [comment]
Could it be that there are more undocumented dependencies? I am getting

* poppler-qt5.h: No such file or directory
* Qsci/qsciscintilla.h: No such file or directory

Are there more?

**Comment by marcusbritanicus** [comment]
There could surely be. The dependencies are mainly

- Qt4/Qt5 (including QtXml, QtWebKit/QtWebEngine, QtNetwork, QtWebChannel)
- LibArchive (libarchive-dev)
- zlib (zlib1g-dev)
- bzip2 (libbz2-dev)
- lzma2 (liblzma-dev)
- xdg-utils (specifically xdg-open)
- Poppler-Qt (libpoppler-qt4-dev, libpoppler-qt5-dev)
- DjVu (libdjvulibre-dev)

**Comment by probonopd** [comment]
Added more dependencies to https://github.com/probonopd/NewBreeze/blob/patch-1/.travis.yml

Let's see how it goes at https://travis-ci.org/probonopd/NewBreeze/builds/346034296
