### ISSUE TITLE
AppImage does not run

### ISSUE THREAD

**Issue by probonopd** [marcusbritanicus/NewBreeze#23]
AppImage does not run on Ubuntu 14.04 (trusty), a still-supported Ubuntu version:

```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

Reference: https://travis-ci.org/AppImage/appimage.github.io/builds/346437970#L595

**Comment by probonopd** [comment]
When running locally on an Ubuntu 16.04 machine, I get

```
me@host:~/squashfs-root$ /home/me/Downloads/NewBreeze-x86_64.AppImage
NewBreeze::FatalError# This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted
```

How was this AppImage produced?

**Comment by marcusbritanicus** [comment]
I did use linuxdeployqt. But since my system is Debian Sid, it may not work on older systems. Its may be the same reason why xcb is not working.

**Comment by probonopd** [comment]
Most definitely. Let's get it to build on trusty.

**Comment by marcusbritanicus** [comment]
I'll be trying to compile it on Trusty today. I'll let you know if its successful.

**Comment by marcusbritanicus** [comment]
I could comfortably compile NB3 ([latest commit](https://github.com/marcusbritanicus/NewBreeze/commit/91b078e22cde9c5b0054db1c0bc89cd16bf1417e)). The following are the changes I had to make:

1. NB3-Common compiled smoothly without changes.
2. Enable `QMAKE_CXXFLAGS += -std=c++11` in app.pro because of `nullptr` in Salsa.hpp
3. `QtWebEngine` is not available in Trusty. I had to disable `NBWebWatch` in `Defaults` plugin and disable `MarkDown` plugin itself.
4. In `NBArchiveTreeModel.cpp` despite libarchive fix on line 300, it failed to compile. I had to edit the file to change `archive_entry_pathname_utf8(...)` to `archive_entry_pathname(...)`

I hat to install these packages:
1. qtbase5-dev
2. qtbase5-dev-tool
3. libqt5scintilla2-dev
4. libarchive-dev
5. libbz2-dev
6. zlib1g-dev
7. libpoppler-qt5-dev
8. libdjvulibre-dev
9. libqt5webkit5-dev

**Comment by marcusbritanicus** [comment]
Here are a two screenshots.

![screenshot from 2018-02-28 10 04 28](https://user-images.githubusercontent.com/3350667/36803069-944086e4-1cdc-11e8-9a16-b7a5b56a8922.png)
![screenshot from 2018-02-28 10 05 53](https://user-images.githubusercontent.com/3350667/36803071-94cbc0f6-1cdc-11e8-9d8c-2f3e9e0f0f5d.png)

**Comment by rahmanshaber** [comment]
will you update the dependencies list??
as some of them is missing is start page??

**Comment by marcusbritanicus** [comment]
I have updated the readme files.

**Comment by probonopd** [comment]
> Enable QMAKE_CXXFLAGS += -std=c++11 in app.pro because of nullptr in Salsa.hpp
QtWebEngine is not available in Trusty. I had to disable NBWebWatch in Defaults plugin and disable MarkDown plugin itself.
> In NBArchiveTreeModel.cpp despite libarchive fix on line 300, it failed to compile. I had to edit the file to change archive_entry_pathname_utf8(...) to archive_entry_pathname(...)

Did you commit those changes, so that when I compile the unchanged source code it is expected to work?

**Comment by marcusbritanicus** [comment]
Yes I have committed these changes. I'm expecting it to work.

**Comment by rahmanshaber** [comment]
how did u made yor appimage??
by linuxdeployqt or Travis CI?
if Travis CI , how you got the appimage build by Travis CI in your hand?

**Comment by marcusbritanicus** [comment]
I still have not managed to get a working appimage. TravisCI also uses linuxdeployqt. On travisCI it fails to create an AppImage. Manually when I tried, I was able to create the appimage, however, it never worked. It would give floating point exception and fail. So I am currently not trying to make an appimage.

**Comment by rahmanshaber** [comment]
but the app image is working in my system great.even now start menu has the app icon.
how you created your appimage??
i am thinking to make an appimage of piBreeze .
because my pi dose not connected to net .
also if you tell me the steps i would like to make a tutorial out of it.
thanks.

**Comment by marcusbritanicus** [comment]
The binary I had given you was not the AppImage. It was just a plain compiled binary. There was a desktop file because of which icon remains in the menu.

**Comment by rahmanshaber** [comment]
no 
i downloaded from release.

**Comment by rahmanshaber** [comment]
i know it will not work in r-pi
it worked in my system perfectly.
only superstart not working at all
