### ISSUE TITLE
Can't compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [marcusbritanicus/NewBreeze#24]
Can't compile on Ubuntu 14.04:
https://travis-ci.org/probonopd/NewBreeze/builds/346439041

Any help is appreciated.

**Comment by marcusbritanicus** [comment]
`archive_entry_pathname_utf8(...)` was unavailable in Ubuntu 14.04. It was introduced after libarchive 3.1.6, but in U14.04 libarchive is still in 3.1.2. I've fixed this.

**Comment by marcusbritanicus** [comment]
`archive_entry_pathname_utf8(...)` was unavailable in Ubuntu 14.04. It was introduced after libarchive 3.1.6, but in U14.04 libarchive is still in 3.1.2. I've fixed this. However, I haven't the faintest idea why `Qsci/qsciscintilla.h: No such file or directory` error is showing.

**Comment by marcusbritanicus** [comment]
I managed to get it compiling on Trusty. Check these comments on the other issue.
[Compiling on Trusty](https://github.com/marcusbritanicus/NewBreeze/issues/23#issuecomment-369257610)
[Screenshots on Trusty](https://github.com/marcusbritanicus/NewBreeze/issues/23#issuecomment-369320650)

**Comment by probonopd** [comment]
Great that it is working. Is it possible to compile on trusty now without changing the content of any of the files in this repository? Maybe IFDEFs or something like that could be used, if you haven't done so already.

**Comment by marcusbritanicus** [comment]
I have committed some changes. These should enable NewBreeze to compile on Trusty without any modifications to the source.

**Comment by probonopd** [comment]
Thanks, next build started: https://travis-ci.org/probonopd/NewBreeze/builds/348748861

**Comment by marcusbritanicus** [comment]
I think it might be better to use `libqscintilla2-qt5-dev` in place of `libqt5scintilla2-dev` if it is available.

**Comment by marcusbritanicus** [comment]
Looks like there is a problem with the package `libqt5scintilla2-dev` and `ibqscintilla2-qt5-dev` isn't available in trusty.

**Comment by probonopd** [comment]
Now I am a bit confused, I think you had it compile on trusty?

**Comment by marcusbritanicus** [comment]
So am I. I downloaded the latest live cd and installed the same set of packages as you have and compiled. Worked like a charm.

**Comment by probonopd** [comment]
Could it be that we need something like `sudo ln -s /usr/include/qt5/Qsci /usr/include/x86_64-linux-gnu/qt5/`? At least this is suggested in https://github.com/openscad/openscad/pull/1778

**Comment by marcusbritanicus** [comment]
Right. Exactly. The Qt5 version you're using is too updated. I did not have access to that (did not add trusty-updates to sources.list). The higher version of Qt5 has `QT_INSTALL_HEADERS` as `/usr/lib/x86_64-linux-gnu/qt5/include`, whereas `libqt5scintilla2-dev` installs in `/usr/include/qt5/`. Thus the issue.

**Comment by marcusbritanicus** [comment]
I think we'll have to open a bug report for `libqt5scintilla2-dev` package. They should do the fixing so that everyone doesn't have to go through this painful patch.

**Comment by probonopd** [comment]
Agree. But first let's see how https://travis-ci.org/probonopd/NewBreeze/builds/348755558 goes.

**Comment by marcusbritanicus** [comment]
Successful build, at last... :)

**Comment by probonopd** [comment]
Err, not really: https://travis-ci.org/probonopd/NewBreeze/builds/348755558#L1435

**Comment by marcusbritanicus** [comment]
I'm not using Qt 5.9, just trusty updates: [Here](https://travis-ci.org/marcusbritanicus/NewBreeze/builds/348861097)

**Comment by probonopd** [comment]
I see, trying to use your configuration now in https://travis-ci.org/probonopd/NewBreeze/builds/348867647

**Comment by marcusbritanicus** [comment]
The reason why linuxdeployqt fails is it never find the `appdir` folder. When the command `make INSTALL_ROOT=appdir` is given, a folder `appdir` is created in each of the subdirs and the respective contents are installed in those appdirs. To get a top-level `appdir` folder, I would suggest `make INSTALL_ROOT=../appdir`

**Comment by marcusbritanicus** [comment]
@probonopd Also I have a query. For some reason, linuxdeployqt seems to think that I need QtQuick libraries and libav and allies too. It pulls in `libQt5Quick.so.5`, `libQt5QuickWidgets.so.5`, `libavcodec.so.57`, `libformat.so.57`, all the way to `libx265.so.146`. Any idea why this happens?

**Comment by marcusbritanicus** [comment]
I have finally succeeded in making the AppImage using travis-ci. [Here](https://travis-ci.org/marcusbritanicus/NewBreeze/builds/349412063) is the successful build where the AppImage is being generated. This is the configuration I used for the successful build:

    language: cpp
    compiler: gcc
    sudo: require
    dist: trusty
    
    before_install:
      - sudo apt-get update -qq
    
    install:
      - sudo apt-get -y install qtbase5-dev libz-dev zlib1g-dev liblz-dev libbz2-dev libarchive-dev xdg-utils libpoppler-qt5-dev libqt5scintilla2-dev libdjvulibre-dev libqt5webkit5-dev
    
    script:
      - qmake -qt5 CONFIG+=release PREFIX=/usr
      - make -j$(nproc)
      - make INSTALL_ROOT=../appdir -j$(nproc) install
      - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
      - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
      - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
      - LD_LIBRARY_PATH="appdir/usr/lib/newbreeze/" ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
      - LD_LIBRARY_PATH="appdir/usr/lib/newbreeze/" ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
    
    branches:
      except:
        - # Do not build tags that we create when we upload to GitHub Releases
        - /^(?i:continuous)/

**Comment by rahmanshaber** [comment]
how u got the appimage in your hand??

On Tue, Mar 6, 2018 at 12:04 AM, Marcus Britanicus <notifications@github.com

**Comment by marcusbritanicus** [comment]
I build the AppImage by hand. The current AppImage is  104 MB because of QtWebEngine. 😠 
I'm not able to upload it. You can check the beta release in another hour or so. If I manage to upload the AppImage, you'll find it under the name `NewBreeze-x86_64-ea786e2.AppImage` If it's not there, it means I have not succeeded in the upload.

**Comment by rahmanshaber** [comment]
did you build it in "Release" mode instead of "Debug"??
"Release" mode ,gives a small size build.

any news in superstar issue ??

On Tue, Mar 6, 2018 at 12:45 AM, Marcus Britanicus <notifications@github.com

**Comment by marcusbritanicus** [comment]
`SuperStart` is fixed. You can compile the latest release. I cannot upload an appimage. Github says no.

**Comment by marcusbritanicus** [comment]
its **SuperStart** and it is fixed. You can compile the latest release. I cannot upload an appimage. Github says no. Also, its not the binary that give the AppImage the size. Its the libraries on which the binary depends on. In my case it depends on QtWebEngine, which is HUGE.

**Comment by probonopd** [comment]
I don't understand why we need `make INSTALL_ROOT=../appdir` but if it helps, then let's use that. 

> For some reason, linuxdeployqt seems to think that I need QtQuick libraries and libav and allies too. It pulls in libQt5Quick.so.5, libQt5QuickWidgets.so.5, libavcodec.so.57, libformat.so.57, all the way to libx265.so.146. Any idea why this happens?

Run `linuxdeployqt` with maximum verbosity and search for the names of these libraries to find out what pulls them in.

**Comment by marcusbritanicus** [comment]
I have install instructions in `NewBreeze/common/common.pro`, `NewBreeze/app/app.pro`, `NewBreeze/plugins/Default.pro`, `NewBreeze/MarkDown/MarkDown.pro`, `NewBreeze/TextEdit/TextEdit.pro`, files. When the command `make INSTALL_ROOT=appdir install` is given, make enters all the subdirs one by one and then executes the command `make INSTALL_ROOT=appdir install` in each of them. So in each of the subdirs a folder called `appdir` is created and the files are installed into that folder. By giving `../appdir` I was able to fix that issue. However, I too find it strange that `../appdir` needs to be given.
