### ISSUE TITLE
super start crashing

### ISSUE THREAD

**Issue by rahmanshaber** [marcusbritanicus/NewBreeze#25]
Linux 4.14, Manjaro linux ,xfce desktop
build fine.when i selected superstar it crashed. 

here is the application output 

`Starting /home/shaber/Downloads/Downloads/Browsers/build-NewBreeze-Desktop-Debug/app/newbreeze3...
NewBreeze::Debug# using qt5ct plugin

NewBreeze::Debug# Added 6742 icons to the database

NewBreeze::Debug# Added 984 mimetypes to the database

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# QSettings::value: Empty key passed

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Debug# D-Bus system tray: no

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Debug# Opening Catalogs

NewBreeze::Warning# QSettings::value: Empty key passed

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Debug# Opening SuperStart

NewBreeze::Warning# QSettings::value: Empty key passed

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

NewBreeze::Warning# libpng warning: iCCP: known incorrect sRGB profile

The program has unexpectedly finished.
The process was ended forcefully.
/home/shaber/Downloads/Downloads/Browsers/build-NewBreeze-Desktop-Debug/app/newbreeze3 crashed.`

**Comment by marcusbritanicus** [comment]
Hmm.. I'm not very sure why this is happening. I've tried compiling it on a clean system (Ubuntu Trusty on VBox). Everything has worked as it should. Compilation was a bit of an issue. I'll be pushing the changes shortly.

**Comment by rahmanshaber** [comment]
I am here for two feature ,one superstar ,second encrypted folder.
So please, do something to fix superstar.

**Comment by marcusbritanicus** [comment]
Please try and compile the latest commit. Remove all the configuration files of newbreeze: They'll be in ~/.config/NewBreeze. In my view, the only issue with SuperStart was indirectly because of NBDeviceInfo. That issue has been fixed. If the issue persists, please post the output of  `mount`. There might be other virtual fs which might be causing the crashes.

**Comment by rahmanshaber** [comment]
lastes build is not solving the crash.
out put of mount

[shaber@shaber-pc ~]$ mount
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sys on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
dev on /dev type devtmpfs
(rw,nosuid,relatime,size=2955104k,nr_inodes=738776,mode=755)
run on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
/dev/sda1 on / type ext4 (rw,noatime,data=ordered)
securityfs on /sys/kernel/security type securityfs
(rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts
(rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/unified type cgroup2
(rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup
(rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/devices type cgroup
(rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup
(rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/rdma type cgroup
(rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/perf_event type cgroup
(rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/freezer type cgroup
(rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup
(rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup
(rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/cpuset type cgroup
(rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/pids type cgroup
(rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/blkio type cgroup
(rw,nosuid,nodev,noexec,relatime,blkio)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs
(rw,relatime,fd=24,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=10427)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
configfs on /sys/kernel/config type configfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
tmpfs on /run/user/1000 type tmpfs
(rw,nosuid,nodev,relatime,size=592356k,mode=700,uid=1000,gid=1000)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse
(rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/sda2 on /run/media/shaber/Storage type ext4
(rw,nosuid,nodev,relatime,data=ordered,uhelper=udisks2)


On Thu, Mar 1, 2018 at 12:20 PM, Marcus Britanicus <notifications@github.com

**Comment by marcusbritanicus** [comment]
Caught the issue. When you run any AppImage, it creates a virtual mount at /tmp/.mount_XXXXX. This causes NewBreeze to crash. I'll be uploading a fix and the AppImage shortly.

To create an AppImage do the following. Compile NewBreeze:

    $ qmake -qt5
    $ make

Then you need to copy all the files in the proper hierarchy (i.e. /usr/bin/newbreeze3, /usr/share/applications/newbreeze.desktop, etc) To do that:

    $ make INSTALL_ROOT=/tmp/NB3 install

You can replace `/tmp/NB3` by any path, make sure its an absolute path (starts with `/`).
Then run linuxdeployqt:

    $ linuxdeployqt-continuous-x86_64.AppImage /tmp/NB3/usr/share/applications/newbreeze.desktop

It will take a while for this to complete. And the AppImage will be ready.

**Comment by rahmanshaber** [comment]
sorry for my ignorance
what you are talking about "need to copy all the files in the proper
hierarchy"

On Mon, Mar 5, 2018 at 10:43 PM, Marcus Britanicus <notifications@github.com

**Comment by marcusbritanicus** [comment]
To create a proper AppImage, you need files in their proper positions: binaries in /usr/bin, shared objects in /usr/lib, desktop files in /usr/share/applications, and so on. This structure:
/ -> /usr -> /usr/bin, /usr/share.... is called the hierarchy.
