### ISSUE TITLE
request for default themes

### ISSUE THREAD

**Issue by rahmanshaber** [marcusbritanicus/NewBreeze#26]
thanks for all the great work.
it would be great if two default themes is available.
dark and light.
i know i could do it with system themes. but system theme dose not work great with community/external  app.
but if it could be done in the app ,it will look great.Please consider to doing it.
great example is this app (https://github.com/oguzhaninan/Stacer)
thanks.

**Comment by marcusbritanicus** [comment]
I'm not planning on adding inbuilt themes until v4.0 Till then I'm afraid system you'll have manage with system themes.

**Comment by marcusbritanicus** [comment]
This issue will be pursued on [GitLab](https://gitlab.com/marcusbritanicus/NewBreeze/issues/26)
